#! /bin/sh

set -e

if [ "$1" = purge ]; then
    rm -rf /var/lib/binfmts
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d binfmt-support remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
